<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Are you sure you want to delete this item?' => 'Bu obyekti silməkdə əminsiniz?',
  'Delete' => 'Sil',
  'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => '{count} nəticədən {start}-{end} arası göstərilir.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'CDataColumn dəyəri  üçün "name" və ya "value" təyin olunmalıdır.',
  'Home' => 'Ana səhifə',
  'No results found.' => 'Nəticə tapılmadı',
  'Not set' => 'Mənimsədilmədi',
  'Please specify the "attributes" property.' => 'Zəhmət olmasa "attributes" təyin edin.',
  'Please specify the "data" property.' => 'Zəhmət olmasa "data" dəyərin təyin edin.',
  'Sort by: ' => 'Sırala: ',
  'The "dataProvider" property cannot be empty.' => '"dataProvider" dəyəri boş olmamalıdır.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Değer, "Type" ve "Label" \'ın opsiyonel olduğu durumda, "Name:Type:Label" formatında tanımlanmalıdır.',
  'The button type "{type}" is not supported.' => '"{type}" buton tipi desteklenmemektedir.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Sütun, "Type" ve "Label" \'ın opsiyonel olduğu durumda, "Name:Type:Label" formatında tanımlanmalıdır.',
  'The property "itemView" cannot be empty.' => '"itemView" dəyəri boş olmamalıdır.',
  'Total 1 result.|Total {count} results.' => 'Ümumi nəticə: {count}.',
  'Update' => 'Yenilə',
  'View' => 'Görüntü',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} üçün "model" ve "attribute" və ya "name" dəyərləri təyin edilməlidir.',
);
